apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: argocd-install
version: 0.1.0
dependencies:
- name: argo-cd
  version: "3.17.6"
  repository: "https://argoproj.github.io/argo-helm/"