argo-cd:
  server:
    configEnabled: true
    additionalApplications: 
      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          helm:
            version: v3
            valueFiles:
            - values.yaml
            - ../values-override.yaml
          path: argocd-install/argo-cd
          repoURL: https://github.com/kurtburak/argocd.git
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
      - name: argocd-apps
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: argocd-apps
          repoURL: https://github.com/kurtburak/argocd.git
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: {}
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
      - name: argocd-appprojects
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: argocd-appprojects
          repoURL: https://github.com/kurtburak/argocd.git
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: {}
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
    additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false
  configs:
    repositories:
      kurtburak-argocd:
        url: https://github.com/kurtburak/argocd.git
        name: kurtburak-argocd
        type: git
      soichisumi-sandbox-argocd:
        url: https://github.com/soichisumi-sandbox/envoyfilter-sandbox.git
        name: envoyfilter-sandbox
        type: git
    