apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: istio
  source:
    path: istio-helm/
    repoURL: https://github.com/soichisumi-sandbox/envoyfilter-sandbox.git
    targetRevision: HEAD
    helm:
      version: "v2"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-init
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: istio
  source:
    path: istio-init-helm/
    repoURL: https://github.com/soichisumi-sandbox/envoyfilter-sandbox.git
    targetRevision: HEAD
    helm:
      version: "v2"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-server
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mock-server/
    repoURL: https://github.com/soichisumi-sandbox/envoyfilter-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true